[package]
name = "chamomile"
version = "0.8.0"
authors = ["Dev <dev@cympletech.com>"]
readme = "README.md"
description = "Another P2P Library. Support IoT devices."
repository = "https://github.com/cympletech/chamomile"
keywords = ["distributed", "blockchain", "p2p", "libp2p", "peer-to-peer"]
license = "MIT/Apache-2.0"
edition = "2021"

[workspace]
members = [
    "types",
]

[dependencies]
rand = "0.7"
log = "0.4"
bit-vec = "0.6"
x25519-dalek = "1.2"
aes-gcm = "0.9"
rcgen = "0.9"
structopt = "0.3"
thiserror = "1.0"
webpki = "0.22"
quinn-proto = "0.8"
futures-util = { version = "0.3", default-features = false }
tokio = { version = "1", features = ["full"] }
bytes = {version = "1.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
rustls = { version = "0.20", features = ["dangerous_configuration"] }
quinn = { version = "=0.8.0", features = ["tls-rustls"], default-features = false }
zeroize = { version = "1", features = ["zeroize_derive"] }
chamomile_types = { version = "0.8", path = "./types" }

[dev-dependencies]
simplelog = "0.11"
console-subscriber = "0.1"