[package]
name = "chamomile"
version = "0.1.0"
authors = ["Sun <huachuang20@gmail.com>"]
edition = "2018"
readme = "README.md"
description = "p2p library"
repository = "https://github.com/placefortea/chamomile"
keywords = ["distributed", "blockchain", "infrastructure", "p2p", "libp2p"]
license = "MIT/Apache-2.0"

[dependencies]
serde = "1"
serde_derive = "1"
bytes = "0.4"

# tokio
tokio = "0.1"
futures = "0.1"
actix = "0.8"
rckad = "0.0.3"

# crypto
rsa = "0.1"
ed25519-dalek = "1.0.0-pre.0"
libsecp256k1 = "0.2"

# serializtion

# transport

# rpc

[dev-dependencies]

