[package]
name = "chamomile"
version = "0.1.0"
authors = ["Sun <huachuang20@gmail.com>"]
edition = "2018"
readme = "README.md"
description = "p2p library"
repository = "https://github.com/placefortea/chamomile"
keywords = ["distributed", "blockchain", "infrastructure", "p2p", "libp2p"]
license = "MIT/Apache-2.0"

[dependencies]
lazy_static = "1.3"
toml = "0.5"

# runtime
actix = "0.8"
tokio = "0.1"
futures = "0.1"
crossbeam-channel = "~0.3.8"

# Protocol Lab
multiaddr = "*"

# crypto
rsa = "0.1"
ed25519-dalek = "1.0.0-pre.0"
libsecp256k1 = "0.2"

# DHT & NAT
rckad = "0.0.5"

# serializtion
bytes = { version = "0.4", features = ["serde"] }
serde = "1"
serde_derive = "1"
bincode = "1"

## transport
# QUIC
quinn = "~0.3.0"
rcgen = "0.4"
webpki = "0.19"
rustls = { version = "0.15.2", features = ["quic", "dangerous_configuration"] }

# TCP
socket2 = "0.3"
yamux = { git = "https://github.com/paritytech/yamux", version = "0.2.1" }

# KCP
#kcp = { path = "../kcp" }

# rpc

[dev-dependencies]

