[package]
name = "chamomile"
version = "0.6.3"
authors = ["Contact <contact@cypherlink.io>"]
readme = "README.md"
description = "Another P2P Library. Support IoT devices."
repository = "https://github.com/cypherlink/chamomile"
keywords = ["distributed", "blockchain", "p2p", "libp2p", "peer-to-peer"]
license = "MIT/Apache-2.0"
edition = "2018"

[workspace]
members = [
    "types",
]

[dependencies]
toml = "0.5"
rand = "0.7"
log = "0.4"
bit-vec = "0.6"
blake3 = "1.0"
ed25519-dalek = "1.0"
x25519-dalek = "1.1"
aes-gcm = "0.9"
rcgen = "0.8"
structopt = "0.3"
thiserror = "1.0"
webpki = "0.21"
quinn-proto = "0.7"
futures-util = { version = "0.3", default-features = false }
tokio = { version = "1", features = ["full"] }
bytes = {version = "1.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
rustls = { version = "0.19", features = ["dangerous_configuration"] }
quinn = { version = "0.7", features = ["tls-rustls"], default-features = false }
zeroize = { version = "1", features = ["zeroize_derive"] }
chamomile_types = { version = "0.6", path = "./types" }

[dev-dependencies]
simplelog = "=0.10.0"
