[package]
name = "chamomile"
version = "0.1.0"
authors = ["Contact <contact@cypherlink.io>"]
readme = "README.md"
description = "Another P2P Library. Support IoT devices."
repository = "https://github.com/cypherlink/chamomile"
keywords = ["distributed", "blockchain", "infrastructure", "p2p", "libp2p"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
lazy_static = "1.3"
toml = "0.5"
rand = "0.7"

# async runtime and channel
futures = "0.3"
async-std = { version = "1", features = ["unstable"] }
async-trait = "0.1"

# crypto
sha3 = "0.8"
ed25519-dalek = "1.0.0-pre.3"
aes-soft = "0.3"

# DHT & NAT
rckad = "0.0.5"

# serializtion
serde = "1"
serde_derive = "1"
bincode = "1"

## transport
# QUIC
#quinn = "~0.3.0"
rcgen = "0.4"
#webpki = "0.19"
#rustls = { version = "0.15.2", features = ["quic", "dangerous_configuration"] }

# TCP
#socket2 = "0.3"
#yamux = { git = "https://github.com/paritytech/yamux", version = "0.2.1" }

# KCP
#kcp = { path = "../kcp" }

# rpc

[dev-dependencies]

