[package]
name = "chamomile"
version = "0.2.0"
authors = ["Contact <contact@cypherlink.io>"]
readme = "README.md"
description = "Another P2P Library. Support IoT devices."
repository = "https://github.com/cypherlink/chamomile"
keywords = ["distributed", "blockchain", "p2p", "libp2p", "peer-to-peer"]
license = "MIT/Apache-2.0"
edition = "2018"

[workspace]
members = [
    "types",
]

[dependencies]
chamomile_types = "0.2"

toml = "0.5"
rand = "0.7"
sled = "0.34"
log = "0.4"

# async runtime and channel
smol = "1.0"

# crypto
sha3 = "0.9"
ed25519-dalek = "1.0"
x25519-dalek = "1.1"
aes-soft = "0.5"
block-modes = "0.6"

# DHT & NAT
rckad = "0.1"

# serializtion
serde = { version = "1.0", features = ["derive"]}
postcard = { version = "0.5", default-features = false, features = ["alloc"] }

## transport
# QUIC
#quinn = "~0.3.0"
#webpki = "0.19"
#rustls = { version = "0.15.2", features = ["quic", "dangerous_configuration"] }

# TCP
#socket2 = "0.3"
#yamux = { git = "https://github.com/paritytech/yamux", version = "0.2.1" }

# KCP
#kcp = { path = "../kcp" }

# rpc

[dev-dependencies]
simplelog = "0.7"
