[package]
name = "chamomile"
version = "0.2.0"
authors = ["Contact <contact@cypherlink.io>"]
readme = "README.md"
description = "Another P2P Library. Support IoT devices."
repository = "https://github.com/cypherlink/chamomile"
keywords = ["distributed", "blockchain", "p2p", "libp2p", "peer-to-peer"]
license = "MIT/Apache-2.0"
edition = "2018"

[workspace]
members = [
    "types",
]

[dependencies]
chamomile_types = { version = "0.2", path = "./types" }
toml = "0.5"
rand = "0.7"
log = "0.4"
bit-vec = "0.6"

# crypto
blake3 = "0.3"
ed25519-dalek = "1.0"
x25519-dalek = "1.1"
aes-soft = "0.6"
block-modes = "0.7"

# async runtime and channel
smol = "1.2"

[dev-dependencies]
simplelog = "0.8"
