[package]
name = "chamomile-types"
version = "0.4.0"
authors = ["Contact <contact@cypherlink.io>"]
readme = "README.md"
description = "Another P2P Library. Support IoT devices."
repository = "https://github.com/cypherlink/chamomile"
keywords = ["distributed", "blockchain", "p2p", "libp2p", "peer-to-peer"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
async-channel = "1.5"
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"]}
